# -*- coding: utf-8 -*-
"""IR_HW5_Q1_PreProcess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lz5k-Karf-8x31Q9ojSmfv67G5yH4d3_
"""

import nltk
nltk.download('popular')

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

def tokenize(column):
    """Tokenizes a Pandas dataframe column and returns a list of tokens.

    Args:
        column: Pandas dataframe column (i.e. df['text']).

    Returns:
        tokens (list): Tokenized list, i.e. [Donald, Trump, tweets]

    """

    tokens = nltk.word_tokenize(column)
    return [w for w in tokens if w.isalpha()]

def remove_stopwords(tokenized_column):
    """Return a list of tokens with English stopwords removed.

    Args:
        column: Pandas dataframe column of tokenized data from tokenize()

    Returns:
        tokens (list): Tokenized list with stopwords removed.

    """
    stops = set(stopwords.words("english"))
    return [word for word in tokenized_column if not word in stops]

def apply_stemming(tokenized_column):
    """Return a list of tokens with Porter stemming applied.

    Args:
        column: Pandas dataframe column of tokenized data with stopwords removed.

    Returns:
        tokens (list): Tokenized list with words Porter stemmed.

    """

    stemmer = PorterStemmer()
    return [stemmer.stem(word) for word in tokenized_column]

from google.colab import drive
drive.mount('/content/drive')

data_file = "/content/drive/MyDrive/BA_AirlineReviews.csv"
data = pd.read_csv(data_file)
# data.head()

data.head()

"""# Tokenizing"""

# data.insert(7 , 'ReviewBodyPreProcess' , '')

data['tokenized'] = data.apply(lambda x: tokenize(x['ReviewBody']), axis=1)
data[['ReviewBody', 'tokenized']].head()

"""# Remove Stopwords"""

data['stopwords_removed'] = data.apply(lambda x: remove_stopwords(x['tokenized']), axis=1)
data[['ReviewBody', 'stopwords_removed']].head()

"""# Stemming"""

data['porter_stemmed'] = data.apply(lambda x: apply_stemming(x['stopwords_removed']), axis=1)
# data[['Review', 'porter_stemmed']].head()

data[['ReviewBody', 'porter_stemmed']].tail()

data['ReviewBodyPreProcess'] = data['porter_stemmed']

# data.insert(7 , 'RemovedStopWords' , '')

# data['RemovedStopWords'] = data.apply(lambda x: remove_stopwords(x['ReviewBody']), axis=1)

# data.head()

data.drop('RemovedStopWords' , axis = 1)

"""# Exporting from dataframe"""

data.to_csv("BA_AirlineReviews_output.csv" , index = False)